-- CreateTable
CREATE TABLE "public"."USUARIO" (
    "ID_USUARIO" SERIAL NOT NULL,
    "CD_LOGIN" TEXT NOT NULL,
    "CD_SENHA" TEXT NOT NULL,
    "NR_SALDO" INTEGER NOT NULL,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_CD_LOGIN_key" ON "public"."USUARIO"("CD_LOGIN");
